export enum GlobalConfig {
  DAY_FORMAT = 'YYYY-MM-DD',
  MONTH_FORMAT = 'YYYY-MM',
  DAYTIME_FORMAT = 'YYYY-MM-DDTHH:mm:ss',
  DAYTIME_FORMAT_SHORT = 'MM-DD HH:mm',
  USER_SESSION_EXPIRE_IN_HOURS = 48,
  MAX_FILE_SIZE = 10000000,
}
