FROM node:18-alpine AS builder

COPY @types @types

WORKDIR /server

COPY server/tsconfig.json tsconfig.json
COPY server/package.json package.json
COPY server/@utils @utils
COPY server/service-users/package.json service-users/package.json

RUN npm install

COPY server/service-users service-users

RUN npm run tsc --workspace=service-users

EXPOSE 3000

CMD npm run prod --workspace=service-users
