FROM node:18-alpine AS builder

COPY @types @types

WORKDIR /gateway

COPY gateway/tsconfig.json tsconfig.json
COPY gateway/package.json package.json

RUN npm install

COPY gateway/src src

RUN npm run tsc

EXPOSE 3000

CMD npm run prod
