FROM node:18-alpine AS builder

COPY @types @types

WORKDIR /server

COPY server/tsconfig.json tsconfig.json
COPY server/package.json package.json
COPY server/@utils @utils
COPY server/service-email/package.json service-email/package.json

RUN npm install

COPY server/service-email service-email

RUN npm run tsc --workspace=service-email

EXPOSE 3000

CMD npm run prod --workspace=service-email
