name: Deploy
on:
  push:
    branches:
      - release/**
jobs:
  lint-server:
    uses: ./.github/workflows/lint-server.yml
  lint-gateway:
    uses: ./.github/workflows/lint-gateway.yml
  deploy-gateway:
    needs:
      - lint-gateway
    uses: ./.github/workflows/deploy-gateway.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  deploy-files:
    needs:
      - lint-server
    uses: ./.github/workflows/deploy-files.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  deploy-email:
    needs:
      - lint-server
    uses: ./.github/workflows/deploy-email.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  deploy-users:
    needs:
      - lint-server
    uses: ./.github/workflows/deploy-users.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
