name: Lint gateway
on:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: npm --prefix ./gateway ci
      - run: npm --prefix ./gateway run lint
