name: Pull request
on:
  pull_request:
jobs:
  lint-client:
    uses: ./.github/workflows/lint-client.yml
  lint-gateway:
    uses: ./.github/workflows/lint-gateway.yml
  lint-server:
    uses: ./.github/workflows/lint-server.yml
